# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create! email: 'thomas.taege@eneraque.com', password: 'M3ad0wmuff!n', password_confirmation: 'M3ad0wmuff!n', admin: true, role: 'Management'
user = User.create! email: 'laura.pringle@eneraque.com', password: 'largespeechseendoes', password_confirmation: 'largespeechseendoes', admin: true, role: 'Mangement'
user = User.create! email: 'jeremy.pringle@eneraque.com', password: 'shootlovelycouplerefer', password_confirmation: 'shootlovelycouplerefer', role: 'Mangement'
user = User.create! email: 'aed.mac.phaidin@eneraque.com', password: 'warmsuggestcoalhurried', password_confirmation: 'warmsuggestcoalhurried', role: 'Projects'
user = User.create! email: 'andrew.standley@eneraque.com', password: 'writebarefurtherbread', password_confirmation: 'writebarefurtherbread', role: 'Factory'
user = User.create! email: 'andy.gardner@eneraque.com', password: 'fullyofconnectednoon', password_confirmation: 'fullyofconnectednoon', role: 'Factory'
user = User.create! email: 'antoinette.iles@eneraque.com', password: 'settlersdepthsnaketell', password_confirmation: 'settlersdepthsnaketell', role: 'End User'
user = User.create! email: 'bronte.pringle@eneraque.com', password: 'noddedyoungchartusually', password_confirmation: 'noddedyoungchartusually', role: 'Sales'
user = User.create! email: 'craig.mclauchlan@eneraque.com', password: 'boatwakefunweekend', password_confirmation: 'boatwakefunweekend', role: 'Factory'
user = User.create! email: 'daniel.parker@eneraque.com', password: 'dustgasstarminute', password_confirmation: 'dustgasstarminute', role: 'Sales'
user = User.create! email: 'daniel.woodford@eneraque.com', password: 'fifteenbetweentenfix', password_confirmation: 'fifteenbetweentenfix', role: 'Sales'
user = User.create! email: 'david.cooper@eneraque.com', password: 'severalexclaimedcakenice', password_confirmation: 'severalexclaimedcakenice', role: 'Factory'
user = User.create! email: 'david.leal@eneraque.com', password: 'bigfishjighard', password_confirmation: 'bigfishjighard', role: 'Factory'
user = User.create! email: 'dev.pilcharambath@eneraque.com', password: 'coursenearlyfairterm', password_confirmation: 'coursenearlyfairterm', role: 'Purchasing'
user = User.create! email: 'euan.mcgregor@eneraque.com', password: 'alphabetstopblanksudden', password_confirmation: 'alphabetstopblanksudden', role: 'Sales'
user = User.create! email: 'grant.lihou@eneraque.com', password: 'largereasiertoptie', password_confirmation: 'largereasiertoptie', role: 'Factory'
user = User.create! email: 'guy.pringle@eneraque.com', password: 'floorswungparticularpattern', password_confirmation: 'floorswungparticularpattern', role: 'Sales'
user = User.create! email: 'hilton.cooper@eneraque.com', password: 'beerathertwelveadventure', password_confirmation: 'beerathertwelveadventure', role: 'Factory'
user = User.create! email: 'jim.pringle@eneraque.com', password: 'theyabilitycompletelyhistory', password_confirmation: 'theyabilitycompletelyhistory', role: 'Mangement'
user = User.create! email: 'jonathan.pringle@eneraque.com', password: 'helpfulouteramhot', password_confirmation: 'helpfulouteramhot', role: 'Mangement'
user = User.create! email: 'manfred.beyrer@eneraque.com', password: 'tapebeanfoxfeature', password_confirmation: 'tapebeanfoxfeature', role: 'Projects'
user = User.create! email: 'noel.rosario@eneraque.com', password: 'writinglotworeherself', password_confirmation: 'writinglotworeherself', role: 'Projects'
user = User.create! email: 'ray.verburgt@eneraque.com', password: 'aidlovebroadbuilding', password_confirmation: 'aidlovebroadbuilding', role: 'Projects'
user = User.create! email: 'richard.cranswick@eneraque.com', password: 'believedfunnyoccurcentral', password_confirmation: 'believedfunnyoccurcentral', role: 'End User'
user = User.create! email: 'steve.froome@eneraque.com', password: 'capturedgrasstideprinciple', password_confirmation: 'capturedgrasstideprinciple', role: 'Factory'
user = User.create! email: 'stuart.pringle@eneraque.com', password: 'visitfullygivehope', password_confirmation: 'visitfullygivehope', role: 'Mangement'
user = User.create! email: 'tony.millar@eneraque.com', password: 'camptonightpagedone', password_confirmation: 'camptonightpagedone', role: 'Sales'
user = User.create! email: 'trixie.pringle@eneraque.com', password: 'drinktunepastcertain', password_confirmation: 'drinktunepastcertain', role: 'Sales'
user = User.create! email: 'wesley.mcnaughton@eneraque.com', password: 'amongranchfairlybear', password_confirmation: 'amongranchfairlybear', role: 'Sales'
user = User.create! email: 'william.lister@eneraque.com', password: 'structurenationscorefact', password_confirmation: 'structurenationscorefact', role: 'Factory'
user = User.create! email: 'luminita.kopf@eneraque.com', password: 'powerbellracebelow', password_confirmation: 'powerbellracebelow', role: 'Mangement'
user = User.create! email: 'mohamed.manzoor@eneraque.com', password: 'lookoccurpinktrip', password_confirmation: 'lookoccurpinktrip', role: 'Projects'
user = User.create! email: 'brad.bailey@eneraque.com', password: 'spacelistbellcave', password_confirmation: 'spacelistbellcave', role: 'Projects'
user = User.create! email: 'darren.nankivell@eneraque.com', password: 'amlackwonderverb', password_confirmation: 'amlackwonderverb', role: 'Projects'
user = User.create! email: 'nick.fletcher@eneraque.com', password: 'listbreathpainwrote', password_confirmation: 'listbreathpainwrote', role: 'Projects'
user = User.create! email: 'john.mccarthy@eneraque.com', password: 'suppermasslunchrun', password_confirmation: 'suppermasslunchrun', role: 'Projects'
user = User.create! email: 'rebecca.frost@eneraque.com', password: 'storepocketbirdhouse', password_confirmation: 'storepocketbirdhouse', role: 'End User'
